project:
  type: website
  output-dir: docs

website:
  title: "THE SIRIUS PROJECT"
  navbar:
    left:
      - href: index.qmd
        text: "About"
      - href: sirius_database.qmd
        text: "The Sirius database"
      - href: media.qmd
        text: "The World seen from ..."
      - text: "Synthesis"
        menu:
          - href: Sirius003-regions.qmd  
            text: "Regionalisation"
      - posts.qmd
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/sirius/
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2026, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true



